---
name: 'Run NiFi in tls mode and execute autotests'
description: 'Runs NiFi in tls mode and Consul containers and executes autotests'
inputs:
  results-dir:
    description: 'Directory to store results'
    required: false
    default: 'tls'
runs:
  using: "composite"
  steps:
    - name: Prepare env
      shell: bash
      run: |
        echo "Preparing env..."
        chmod +x .github/workflows/sh/*.sh
        . .github/workflows/sh/nifi-lib.sh
        prepare_sens_key
        prepare_results_dir "${{ inputs.results-dir }}"
        generate_tls_passwords
        create_docker_env_file
        mkdir -p ./temp-vol/tls-cert/
        mkdir -p ./temp-vol/tls-cert/nifi/
        mkdir -p ./temp-vol/tls-cert/nifi-registry/
        mkdir -p ./temp-vol/nifi/per-conf/
        chmod -R 777 ./temp-vol
    - name: Run local nifi
      shell: bash
      run: |
        export NIFI_SENSITIVE_KEY=$(cat ./nifi-sens-key.tmp)
        echo "Starting containers..."
        docker compose -f .github/docker/tls/docker-compose.yaml --env-file ./docker.env up -d
    - name: Wait for nifi container to start
      shell: bash
      continue-on-error: true
      run: |
        . .github/workflows/sh/nifi-lib.sh
        NIFI_CLIENT_PASSWORD=$(cat ./temp-vol/tls-cert/nifi/CN=admin_OU=NIFI.password)
        wait_nifi_container "15" "60" "localhost" "8080" "true" ".github/docker/tls/docker-compose.yaml" "${{ inputs.results-dir }}" \
        "./temp-vol/tls-cert/nifi/nifi-cert.pem" "./temp-vol/tls-cert/nifi/CN=admin_OU=NIFI.p12" \
        "$NIFI_CLIENT_PASSWORD"
    - name: Test log level configuration
      shell: bash
      continue-on-error: true
      run: |
        . .github/workflows/sh/nifi-lib.sh
        test_log_level 'org.qubership.test.pkg2' 'DEBUG' '${{ inputs.results-dir }}' 'local-nifi-tls'
    - name: Run collection for setup policies
      continue-on-error: true
      uses: ./.github/actions/run-newman-tests
      with:
        collection-name: 'Setup_Access_Policies.postman_collection.json'
        env-name: 'NiFi_AT_TLS.json.postman_environment'
        results-dir: '${{ inputs.results-dir }}'
        short-name: 'policies'
        tls-certs-dir: "./temp-vol/tls-cert"
        tls-ca-certs: "nifi/nifi-cert.pem"
        tls-client-certs-config: "newman-tls-config.json"
    - name: Run basic nifi API tests
      continue-on-error: true
      uses: ./.github/actions/run-newman-tests
      with:
        collection-name: 'NiFi_Basic_API_Tests.postman_collection.json'
        env-name: 'NiFi_AT_TLS.json.postman_environment'
        results-dir: '${{ inputs.results-dir }}'
        short-name: 'basic'
        tls-certs-dir: "./temp-vol/tls-cert"
        tls-ca-certs: "nifi/nifi-cert.pem"
        tls-client-certs-config: "newman-tls-config.json"
    - name: Run processors nifi API tests
      continue-on-error: true
      uses: ./.github/actions/run-newman-tests
      with:
        collection-name: 'Check_Processor_API.postman_collection.json'
        env-name: 'NiFi_AT_TLS.json.postman_environment'
        results-dir: '${{ inputs.results-dir }}'
        short-name: 'processors'
        tls-certs-dir: "./temp-vol/tls-cert"
        tls-ca-certs: "nifi/nifi-cert.pem"
        tls-client-certs-config: "newman-tls-config.json"
    - name: Run configuration restore tests (Success case)
      continue-on-error: true
      uses: ./.github/actions/run-conf-restore-test
      with:
        results-dir: '${{ inputs.results-dir }}'
        docker-compose-path: '.github/docker/tls/docker-compose.yaml'
        tls-mode: 'true'
        success-scenario: 'true'
    - name: Run configuration restore tests (Error case)
      continue-on-error: true
      uses: ./.github/actions/run-conf-restore-test
      with:
        results-dir: '${{ inputs.results-dir }}'
        docker-compose-path: '.github/docker/tls/docker-compose.yaml'
        tls-mode: 'true'
        success-scenario: 'false'
    - name: Cleanup after tests
      shell: bash
      continue-on-error: true
      run: |
        export NIFI_SENSITIVE_KEY=$(cat ./nifi-sens-key.tmp)
        echo "Stopping and removing containers"
        docker compose -f .github/docker/tls/docker-compose.yaml --env-file ./docker.env down -v
        sudo rm -rf ./temp-vol/