---
name: 'Run NiFi in plain mode and execute autotests'
description: 'Runs NiFi and Consul containers and executes autotests'
inputs:
  results-dir:
    description: 'Directory to store results'
    required: false
    default: 'plain'
runs:
  using: "composite"
  steps:
    - name: Prepare env
      shell: bash
      run: |
        echo "Preparing env..."
        chmod +x .github/workflows/sh/*.sh
        . .github/workflows/sh/nifi-lib.sh
        prepare_sens_key
        prepare_results_dir "${{ inputs.results-dir }}"
    - name: Run local nifi
      shell: bash
      run: |
        export NIFI_SENSITIVE_KEY=$(cat ./nifi-sens-key.tmp)
        echo "Starting containers..."
        docker compose -f .github/docker/plain/docker-compose.yaml up -d
    - name: Wait for nifi container to start
      shell: bash
      continue-on-error: true
      run: |
        . .github/workflows/sh/nifi-lib.sh
        wait_nifi_container "15" "60" "127.0.0.1" "8080" "false" "local-nifi-plain" "${{ inputs.results-dir }}"
    - name: Test log level configuration
      shell: bash
      continue-on-error: true
      run: |
        . .github/workflows/sh/nifi-lib.sh
        test_log_level 'org.qubership.test.pkg2' 'DEBUG' '${{ inputs.results-dir }}'
    - name: Run basic nifi API tests
      continue-on-error: true
      uses: ./.github/actions/run-newman-tests
      with:
        collection-name: 'NiFi Basic API Tests.postman_collection.json'
        env-name: 'NiFi_AT.json.postman_environment'
        results-dir: '${{ inputs.results-dir }}'
        short-name: 'basic'
    - name: Cleanup after tests
      shell: bash
      continue-on-error: true
      run: |
        export NIFI_SENSITIVE_KEY=$(cat ./nifi-sens-key.tmp)
        echo "Stopping and removing containers"
        docker compose -f .github/docker/plain/docker-compose.yaml down