---
# This GitHub Actions workflow is designed to be triggered when a release is marked as a full release.
# The workflow performs the following tasks:
# - Extract Release Version: Extracts the tag name and removes the leading 'v' character to get the release version.
# - Update pom.xml: Updates the version in the pom.xml file using the extracted release version.
# - Publish to Maven: Publishes the artifact to the Maven repository using the updated pom.xml.

name: Release And Upload to GIT

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '1.0.0'
        type: string
        description: 'Release version (e.g., 1.0.0)'
      java_version:
        required: false
        type: string
        default: "21"
        description: 'Java version (e.g., 21)'
      # upload-artifact:
      #   required: false
      #   type: boolean
      #   default: true
      #   description: 'Upload artifact'
      dry-run:
        required: false
        type: boolean
        default: false
        description: 'Dry run'

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Input parameters
        run: |
          echo "Version: ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Java version: ${{ github.event.inputs.java_version }}" >> $GITHUB_STEP_SUMMARY

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if tag exists
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-checker@main
        with:
          tag: 'v${{ github.event.inputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output result
        run: |
          echo "Tag exists: ${{ steps.check_tag.outputs.exists }}"
          echo "Tag name: v${{ github.event.inputs.version }}"

      - name: Fail if tag exists
        if: steps.check_tag.outputs.exists == 'true'
        run: |
          echo "Tag already exists: v${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Tag already exists: v${{ github.event.inputs.version }}"
          exit 1

  update-pom-version:
    runs-on: ubuntu-latest
    needs: [check-tag]
    outputs:
      artifact_id: ${{ steps.config.outputs.artifact_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update pom.xml
        id: config
        uses: netcracker/qubership-workflow-hub/actions/pom-updater@main
        with:
          new_value: ${{ github.event.inputs.version }}
          file_path: '{"default": "pom.xml", "consul": "./qubership-consul/pom.xml"}'

      - name: Commit Changes
        uses: netcracker/qubership-workflow-hub/actions/commit-and-push@main
        with:
          commit_message: "Update pom.xml version to ${{ github.event.inputs.version }}"

  mvn-build:
    needs: [update-pom-version]
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
    with:
      maven_command: "--batch-mode package"
      java_version: ${{ github.event.inputs.java_version }}
      version: ${{ github.event.inputs.version }}
      upload-artifact: true
      artifact-id: ${{ needs.update-pom-version.outputs.artifact_id }}
    secrets:
      maven_username: ${{ github.actor }}
      maven_password: ${{ secrets.GITHUB_TOKEN }}
      maven_gpg_passphrase: ${{ secrets.GPG_PHRASE }}
      maven_gpg_private_key: ${{ secrets.GPG_PRIVATE }}

  tests:
    needs: [mvn-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Running tests here"

  tag:
    needs: [tests]
    uses: netcracker/qubership-workflow-hub/.github/workflows/tag-creator.yml@main
    with:
      tag-name: ${{ github.event.inputs.version }}

  mvn-publish:
    needs: [update-pom-version, tag]
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
    with:
      maven_command: ${{ (github.event.inputs.dry-run == 'true' && '--batch-mode package') || 'X --batch-mode deploy' }}
      java_version: ${{ github.event.inputs.java_version }}
      version: ${{ github.event.inputs.version }}
      upload-artifact: false
      artifact-id: ${{ needs.update-pom-version.outputs.artifact_id }}
    secrets:
      maven_username: ${{ github.actor }}
      maven_password: ${{ secrets.GIT_MVN_TOKEN }}
      maven_gpg_passphrase: ${{ secrets.GPG_PHRASE }}
      maven_gpg_private_key: ${{ secrets.GPG_PRIVATE }}

  docker-build-publish:
    needs: [update-pom-version, tag]
    uses: netcracker/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
    with:
      ref: ${{ github.event.inputs.version }}
      artifact-id: ${{ needs.update-pom-version.outputs.artifact_id }}
      dry-run: ${{ inputs.dry-run }}

  github-release:
    needs: [tag]
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      publish: false